# Generated by Django 5.1.1 on 2024-10-09 01:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'Nome inválido.'}, max_length=45, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'nome deve ter de 2 a 45 caracteres.'), django.core.validators.RegexValidator('^[\\w ]+$', 'Nome inválido.')], verbose_name='Nome')),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to='products/thumbs/%Y-%m')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'O nome da categoria é inválido.'}, max_length=45, validators=[django.core.validators.RegexValidator('^[\\w ]+', 'O nome da categoria é inválido.')], verbose_name='Nome')),
                ('products', models.ManyToManyField(related_name='categories', related_query_name='category', to='products.product')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nome')),
                ('size', models.CharField(max_length=4, verbose_name='Tamanho')),
                ('color', models.CharField(max_length=20, verbose_name='Cor')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, error_messages={'invalid': 'Preço inválido.'}, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Estoque')),
                ('products', models.ManyToManyField(related_name='variations', related_query_name='variation', to='products.product')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
