# Generated by Django 5.1.1 on 2024-10-13 01:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'O nome da categoria é inválido.'}, max_length=45, validators=[django.core.validators.RegexValidator('^[\\w ]+', 'O nome da categoria é inválido.')], verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'Nome inválido.'}, max_length=45, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'nome deve ter de 2 a 45 caracteres.'), django.core.validators.RegexValidator('^[\\w ]+$', 'Nome inválido.')], verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('thumbnail', models.ImageField(upload_to='products/thumbs/%Y-%m')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('categories', models.ManyToManyField(related_name='cat_products', related_query_name='cat_product', to='products.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nome')),
                ('size', models.CharField(max_length=4, verbose_name='Tamanho')),
                ('color', models.CharField(max_length=20, verbose_name='Cor')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, error_messages={'invalid': 'Preço inválido.'}, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
        migrations.CreateModel(
            name='ProductHasVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Produto')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariation', verbose_name='Variação')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(related_name='var_products', related_query_name='var_product', through='products.ProductHasVariation', to='products.productvariation', verbose_name='Variação'),
        ),
    ]
