# Generated by Django 5.1.1 on 2024-10-05 06:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'Nome inválido.'}, max_length=45, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'nome deve ter de 2 a 45 caracteres.'), django.core.validators.RegexValidator('^[\\w ]+$', 'Nome inválido.')], verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=2, error_messages={'invalid': 'Preço inválido.'}, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Estoque')),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to='products/thumbs/%Y-%m')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'O nome da categoria é inválido.'}, max_length=45, validators=[django.core.validators.RegexValidator('^[\\w ]+', 'O nome da categoria é inválido.')], verbose_name='Nome')),
                ('products', models.ManyToManyField(null=True, related_name='categories', related_query_name='category', to='products.product')),
            ],
        ),
    ]
