# Generated by Django 5.1.1 on 2024-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='categories', related_query_name='category', to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nome')),
                ('size', models.CharField(max_length=4, verbose_name='Tamanho')),
                ('color', models.CharField(max_length=20, verbose_name='Cor')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('slug', models.SlugField(unique=True)),
                ('product', models.ManyToManyField(related_name='variations', related_query_name='variation', to='products.product')),
            ],
        ),
    ]
