# Generated by Django 5.1.2 on 2024-10-25 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariationfile',
            name='product_variation_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='options_data', related_query_name='option_data', to='products.productvariationoptiondata', verbose_name='Product variation data'),
        ),
    ]
