# Generated by Django 5.1.2 on 2024-10-17 12:32

import django.core.validators
import utils.support.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='products/thumbs/%Y-%m', validators=[django.core.validators.validate_image_file_extension, utils.support.validators.FileSizeValidator(msg='the file size is too big.', size=5242880)]),
        ),
    ]
