# Generated by Django 5.1.2 on 2024-10-26 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productvariationfile_product_variation_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariationoption',
            options={'verbose_name': 'Product variation option', 'verbose_name_plural': 'Product variation options'},
        ),
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='products', related_query_name='product', to='products.productvariation', verbose_name='Product variations'),
        ),
        migrations.AlterField(
            model_name='productevaluation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evaluations', related_query_name='evaluation', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='productvariationfile',
            name='product_variation_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_files', related_query_name='data_file', to='products.productvariationoptiondata', verbose_name='Product variation data'),
        ),
    ]
