# Generated by Django 5.1.2 on 2024-10-18 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variations', related_query_name='product_variation', to='products.product', verbose_name='Produto'),
        ),
    ]
