# Generated by Django 5.1.2 on 2024-10-25 00:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_productvariationfile_product_variation_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'The number of items is insufficient to create an order.')], verbose_name='Total items')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total amount')),
                ('status', models.CharField(choices=[('PE', 'Order pending'), ('EX', 'Order expired'), ('CA', 'Order canceled'), ('PA', 'Order paid')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order', verbose_name='Order')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariation', verbose_name='Product variation')),
            ],
            options={
                'verbose_name': 'Order product variation',
                'verbose_name_plural': 'Order product variations',
            },
        ),
    ]
