# Generated by Django 5.1.1 on 2024-10-13 01:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'O status é inválido.'}, max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[\\w ]+$', 'O status é inválido.')], verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Status de pedido',
                'verbose_name_plural': 'Status de pedidos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField(default=1, verbose_name='Qtd.')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('stripe_payment_id', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^pi_[A-Za-z0-9]+$', 'O id do pagamento é inválido.')])),
                ('stripe_payment_method_id', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^pm_[A-Za-z0-9]+$', 'O id do método de pagamento é inválido.')])),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariation', verbose_name='Variação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orderstatus')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
