# Generated by Django 5.1.2 on 2024-10-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_method_id',
        ),
    ]
