# Generated by Django 5.1.2 on 2024-10-18 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_stripe_payment_id_and_more'),
        ('products', '0003_alter_productvariation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='product_variation_order', to='products.productvariation', verbose_name='Variação'),
        ),
    ]
