# Generated by Django 5.1.1 on 2024-10-04 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'O nome da loja é inválido'}, max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[\\w ]+$')], verbose_name='Nome')),
                ('slogan', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='')),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
    ]
