# Generated by Django 5.1.1 on 2024-10-13 01:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'O nome da loja é inválido'}, max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[\\w ]+$', 'O nome da loja é inválido'), django.core.validators.MinLengthValidator(2, 'nome deve ter de 2 a 45 caracteres.')], verbose_name='Nome')),
                ('slogan', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(upload_to='store/logos')),
                ('cnpj', models.CharField(error_messages={'invalid': 'CPJ inválido.'}, max_length=14, validators=[django.core.validators.RegexValidator('^\\d+$', 'CPJ inválido.'), django.core.validators.MinLengthValidator(14, 'CPJ inválido.')])),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='StoreHasProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation', verbose_name='Produto')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Loja com produto adquirido',
                'verbose_name_plural': 'Lojas com produto adquirido',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='product_stores', related_query_name='product_store', through='store.StoreHasProductVariation', to='products.productvariation'),
        ),
    ]
