# Generated by Django 5.1.1 on 2024-10-04 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=models.CharField(error_messages={'invalid': 'CPJ inválido, verifique e tente novamente.'}, max_length=14, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
    ]
