# Generated by Django 5.1.2 on 2024-10-17 12:32

import django.core.validators
import utils.support.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(help_text='Max: 5KB', upload_to='store/logos', validators=[utils.support.validators.FileSizeValidator(msg='the file size is too big.', size=5242880), django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(error_messages={'invalid': 'the store name is invalid'}, max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[\\w \\.]+$', 'the store name is invalid'), django.core.validators.MinLengthValidator(2, '`nome` must have between `2` and `45` characters.')], verbose_name='Nome'),
        ),
    ]
