# Generated by Django 5.1.1 on 2024-10-05 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_cnpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=models.CharField(error_messages={'invalid': 'CPJ inválido.'}, max_length=14, validators=[django.core.validators.RegexValidator('^\\d+$', 'CPJ inválido.'), django.core.validators.MinLengthValidator(14, 'CPJ inválido.')]),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(upload_to='store/logos'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(error_messages={'invalid': 'O nome da loja é inválido'}, max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[\\w ]+$', 'O nome da loja é inválido'), django.core.validators.MinLengthValidator(2, 'nome deve ter de 2 a 45 caracteres.')], verbose_name='Nome'),
        ),
    ]
