# Generated by Django 5.1.2 on 2024-10-18 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariation_product'),
        ('store', '0002_alter_store_logo_alter_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='product_has_stores', related_query_name='product_has_store', through='store.StoreHasProductVariation', to='products.productvariation'),
        ),
        migrations.AlterField(
            model_name='storehasproductvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stores', related_query_name='product_store', to='products.productvariation', verbose_name='Produto'),
        ),
    ]
