# Generated by Django 5.1.3 on 2024-11-17 06:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[\\w ,\\.]+$')], verbose_name='Street')),
                ('city', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[\\w ,\\.]+$')], verbose_name='City')),
                ('state', models.CharField(help_text='Ex.: CA', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', 'Invalid state')], verbose_name='State')),
                ('country', models.CharField(help_text='Ex.: US', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', 'Invalid county.')], verbose_name='Country')),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}(-?\\d{3,4})?$')], verbose_name='Postal code')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')], verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[\\w ,\\.]+$')], verbose_name='Complement')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_user_addresses', related_query_name='address_user_address', to='addresses.address', verbose_name='Address')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_address', related_query_name='user_addr', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': "User's address",
                'verbose_name_plural': "User's addresses",
            },
        ),
    ]
