# Generated by Django 5.1.2 on 2024-10-13 23:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[\\w ]$')], verbose_name='Rua')),
                ('state', models.CharField(help_text='Ex.: CA', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', 'Invalid state')], verbose_name='Estado')),
                ('city', models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[\\w ]$')], verbose_name='Cidade')),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}(-?\\d{3,4})?$')], verbose_name='Código postal')),
                ('country', models.CharField(help_text='Ex.: US', max_length=2, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', 'Invalid county.')], verbose_name='País')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='HasAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]+$')], verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[\\w ]$')], verbose_name='Complemento')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='addresses.address')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.store')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço atribuído',
                'verbose_name_plural': 'Endereços atribuídos',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='stores',
            field=models.ManyToManyField(through='addresses.HasAddress', to='store.store'),
        ),
        migrations.AddField(
            model_name='address',
            name='users',
            field=models.ManyToManyField(through='addresses.HasAddress', to=settings.AUTH_USER_MODEL),
        ),
    ]
