# Generated by Django 5.1.2 on 2024-10-17 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hasaddress',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('store__isnull', False), ('user__isnull', True)), models.Q(('store__isnull', True), ('user__isnull', False)), models.Q(('store__isnull', False), ('user__isnull', False)), _connector='OR'), name='chk_has_address_fks_not_given_together'),
        ),
    ]
