# Generated by Django 5.1.1 on 2024-10-13 01:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Image ou video com algum dos seguintes formatos: PNG, JPEG, JPG, WEBP, MP4, AVI, WEBM.', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['PNG', 'JPEG', 'JPG', 'WEBP', 'MP4', 'AVI', 'WEBM'])], verbose_name='Arquivo')),
                ('evaluation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='evaluations.evaluation', verbose_name='Avaliação')),
                ('product_variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productvariation', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Arquivo de mídia',
                'verbose_name_plural': 'Arquivos de mídia',
            },
        ),
    ]
