# Generated by Django 5.1.2 on 2024-10-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_evaluation_description'),
        ('mediafiles', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('evaluation__isnull', True), ('product_variation__isnull', False)), models.Q(('evaluation__isnull', False), ('product_variation__isnull', True), models.Q(('evaluation__isnull', True), ('product_variation__isnull', True), _negated=True)), _connector='OR'), name='chk_mediafile_fks_not_given_together', violation_error_message='The file must be set to evaluation or product.'),
        ),
    ]
