# Generated by Django 5.1.2 on 2024-10-19 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0002_mediafile_chk_mediafile_fks_not_given_together'),
        ('products', '0004_alter_productvariation_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='product_variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variation_mediafiles', to='products.productvariation', verbose_name='Produto'),
        ),
    ]
